services:
    php:
        build:
            context: .
            target: production
            dockerfile: docker/Dockerfile.production
            args:
                uid: ${WWWUSER}
        environment:
            - APACHE_RUN_USER=#${WWWUSER}
            - APACHE_RUN_GROUP=#${WWWUSER}
        ports:
            - '8080:80'
        networks:
            - internal
        volumes:
            - ./:/var/www/html:rw
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:80']
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 10s
        depends_on:
            pnpm:
                condition: service_completed_successfully
    pnpm:
        build:
          context: .
          target: pnpm
          dockerfile: docker/Dockerfile.production
        volumes:
              - ./public:/app/public
        command: /bin/sh -c "rm -rf app/public/build && pnpm run build"
        networks:
            - internal

networks:
    internal:
        name: laravel-cq-net
        driver: bridge
