version: '3'
services:
    nginx:
        container_name: laravel-nginx
        build:
            context: .
            target: nginx
        ports:
            - '8080:8080'
        networks:
            - internal
        volumes:
            - ./:/var/www/html:ro
        depends_on:
            - php

    php:
        container_name: laravel-php
        build:
            context: .
            target: php
        user: '1000:1001'
        networks:
            - internal
        volumes:
            - ./:/var/www/html:rw
networks:
    internal:
        name: laravel-net
        driver: bridge
