services:
    php:
        build:
            context: .
            target: php
            dockerfile: docker/Dockerfile
            args:
                uid: ${WWWUSER}
        environment:
            - APACHE_RUN_USER=#${WWWUSER}
            - APACHE_RUN_GROUP=#${WWWUSER}
        ports:
            - 8080:80
            - 5173:5173
        networks:
            - internal
        volumes:
            - ./:/var/www/html:rw
        restart: unless-stopped

networks:
    internal:
        name: laravel-net
        driver: bridge
