version: '3'
services:
    nginx:
        build:
            context: .
            target: nginx
            dockerfile: docker/Dockerfile
        ports:
            - '8080:8080'
        networks:
            - internal
        volumes:
            - ./:/var/www/html:ro
        depends_on:
            - php
        restart: always

    php:
        build:
            context: .
            target: php
            dockerfile: docker/Dockerfile
        user: '1000:1001'
        networks:
            - internal
        volumes:
            - ./:/var/www/html:rw
        restart: always

networks:
    internal:
        name: laravel-net
        driver: bridge
